groups:
  - name: storyslip-production-alerts
    rules:
      # High-level service availability
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute."

      # API specific alerts
      - alert: APIHighErrorRate
        expr: rate(http_requests_total{job="storyslip-api",status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on StorySlip API"
          description: "API error rate is {{ $value }} errors per second over the last 5 minutes."

      - alert: APIHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="storyslip-api"}[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency on StorySlip API"
          description: "95th percentile latency is {{ $value }}s over the last 5 minutes."

      # Database alerts
      - alert: DatabaseConnectionsHigh
        expr: pg_stat_database_numbackends > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of database connections"
          description: "Database has {{ $value }} active connections."

      - alert: DatabaseSlowQueries
        expr: rate(pg_stat_database_tup_returned[5m]) / rate(pg_stat_database_tup_fetched[5m]) < 0.1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Database queries are slow"
          description: "Database query efficiency is low: {{ $value }}."

      # Memory and CPU alerts
      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.name }}"
          description: "Container {{ $labels.name }} is using {{ $value | humanizePercentage }} of its memory limit."

      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.name }}"
          description: "Container {{ $labels.name }} CPU usage is {{ $value | humanizePercentage }}."

      # Disk space alerts
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space is {{ $value | humanizePercentage }} full."

      # Redis alerts
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis instance is not responding."

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis is using {{ $value | humanizePercentage }} of its memory limit."

      # Widget delivery alerts
      - alert: WidgetDeliveryErrors
        expr: rate(widget_delivery_errors_total[5m]) > 0.05
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High widget delivery error rate"
          description: "Widget delivery error rate is {{ $value }} errors per second."

      # Authentication alerts
      - alert: AuthenticationFailures
        expr: rate(auth_failures_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate is {{ $value }} failures per second."

      # Content management alerts
      - alert: ContentSyncFailures
        expr: rate(content_sync_failures_total[5m]) > 0.02
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Content synchronization failures"
          description: "Content sync failure rate is {{ $value }} failures per second."

      # Business metrics alerts
      - alert: LowUserActivity
        expr: rate(user_actions_total[1h]) < 10
        for: 30m
        labels:
          severity: info
        annotations:
          summary: "Low user activity detected"
          description: "User activity rate is {{ $value }} actions per second over the last hour."

      # Security alerts
      - alert: SuspiciousActivity
        expr: rate(security_events_total{type="suspicious"}[5m]) > 0.01
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Suspicious security activity detected"
          description: "Suspicious activity rate is {{ $value }} events per second."

      # Performance degradation
      - alert: PerformanceDegradation
        expr: |
          (
            histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) /
            histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[1h] offset 1h))
          ) > 1.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Performance degradation detected"
          description: "95th percentile response time has increased by {{ $value }}x compared to 1 hour ago."