global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    service: 'storyslip'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # StorySlip API
  - job_name: 'storyslip-api'
    static_configs:
      - targets: ['api:3001']
    scrape_interval: 15s
    metrics_path: /api/monitoring/metrics
    scrape_timeout: 10s
    honor_labels: true

  # StorySlip Dashboard
  - job_name: 'storyslip-dashboard'
    static_configs:
      - targets: ['dashboard:3002']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # StorySlip Marketing
  - job_name: 'storyslip-marketing'
    static_configs:
      - targets: ['marketing:3003']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /nginx_status

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 30s

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"