# This is a template file - actual secrets should be managed securely
apiVersion: v1
kind: Secret
metadata:
  name: storyslip-secrets
  namespace: storyslip-production
type: Opaque
stringData:
  # Database
  DATABASE_URL: "postgresql://username:password@postgres-service:5432/storyslip_production"
  
  # JWT
  JWT_SECRET: "your-super-secure-jwt-secret-key-here"
  JWT_REFRESH_SECRET: "your-super-secure-jwt-refresh-secret-key-here"
  
  # Supabase
  SUPABASE_URL: "https://your-project.supabase.co"
  SUPABASE_ANON_KEY: "your-supabase-anon-key"
  SUPABASE_SERVICE_ROLE_KEY: "your-supabase-service-role-key"
  
  # Email
  SMTP_HOST: "smtp.sendgrid.net"
  SMTP_PORT: "587"
  SMTP_USER: "apikey"
  SMTP_PASS: "your-sendgrid-api-key"
  FROM_EMAIL: "noreply@storyslip.com"
  
  # AWS (for file uploads and CDN)
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
  AWS_REGION: "us-east-1"
  S3_BUCKET: "storyslip-uploads"
  CLOUDFRONT_DISTRIBUTION_ID: "your-cloudfront-distribution-id"
  
  # Redis (for caching and sessions)
  REDIS_URL: "redis://redis-service:6379"
  
  # Monitoring
  SENTRY_DSN: "your-sentry-dsn"
  
  # Analytics
  GOOGLE_ANALYTICS_ID: "your-ga-id"
  
  # Social Auth (if implemented)
  GOOGLE_CLIENT_ID: "your-google-client-id"
  GOOGLE_CLIENT_SECRET: "your-google-client-secret"
  
  # Webhook secrets
  WEBHOOK_SECRET: "your-webhook-secret-key"
  
  # Encryption
  ENCRYPTION_KEY: "your-32-character-encryption-key"